routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    //ruta del admin

    Route::resource('/resumen', App\Http\Controllers\Admin\ResumenController::class);
    Route::resource('/colaborador', App\Http\Controllers\Admin\ColaboradorController::class);
    Route::resource('/rol', App\Http\Controllers\Admin\RolController::class);
    Route::resource('/socio_comunitario', App\Http\Controllers\Admin\Socio_comunitarioController::class);
    Route::resource('/facultad', App\Http\Controllers\Admin\FacultadController::class);
    Route::resource('/carrera', App\Http\Controllers\Admin\CarreraController::class);
    Route::resource('/tag', App\Http\Controllers\Admin\TagController::class);
    Route::resource('/competencia', App\Http\Controllers\Admin\CompetenciaController::class);
    Route::resource('/proyecto', App\Http\Controllers\Admin\ProyectoController::class);
    Route::resource('/home_noticias', App\Http\Controllers\Admin\Home_noticiasController::class);
    Route::resource('/testimonios', App\Http\Controllers\Admin\TestimoniosController::class);
    Route::resource('/que_hacemos', App\Http\Controllers\Admin\Que_hacemosController::class);
    Route::resource('/quienes_somos', App\Http\Controllers\Admin\Quienes_somosController::class);
    Route::resource('/home_carrusel', App\Http\Controllers\Admin\Home_carruselController::class);
    Route::resource('/ods', App\Http\Controllers\Admin\OdsController::class);
    Route::resource('/user', App\Http\Controllers\Admin\UserController::class);
    Route::resource('/periodo', App\Http\Controllers\Admin\PeriodoController::class);
    Route::resource('/solicitudes', App\Http\Controllers\Admin\SolicitudesController::class);
    Route::resource('/contacto', App\Http\Controllers\Admin\ContactoController::class);
    Route::resource('/area', App\Http\Controllers\Admin\AreaController::class);
    Route::resource('/grafico_carreras', App\Http\Controllers\Admin\GraficoController::class);
    Route::resource('/telefono_area', App\Http\Controllers\Admin\Telefono_areaController::class);
    Route::get('/grafico_carreras', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_carreras'])->name('grafico_carreras');
    Route::get('/grafico_socios', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_socios'])->name('grafico_socios');
    Route::get('/grafico_periodos', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_periodos'])->name('grafico_periodos');
    Route::get('/grafico_tags', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_tags'])->name('grafico_tags');
    Route::get('/grafico_ods', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_ods'])->name('grafico_ods');
});

//ruta publica


Route::get('/', [App\Http\Controllers\FrontController::class, 'home'])->name('/');
Route::get('inicio', [App\Http\Controllers\FrontController::class, 'home'])->name('inicio');
Route::get('/noticias/{slug}', [App\Http\Controllers\FrontController::class, 'noticias'])->name('noticias');
Route::get('/blog-noticias', [App\Http\Controllers\FrontController::class, 'blognoticias'])->name('blog-noticias');
Route::get('/quienes-somos', [App\Http\Controllers\FrontController::class, 'quienes_somos'])->name('quienes-somos');
Route::get('/competencias-genericas', [App\Http\Controllers\FrontController::class, 'competencias'])->name('competencias-genericas');
Route::get('/contacto', [App\Http\Controllers\FrontController::class, 'contacto'])->name('contacto');
Route::get('/proyectos/{id}', [App\Http\Controllers\FrontController::class, 'proyectos'])->name('proyectos');
Route::get('/que-hacemos', [App\Http\Controllers\FrontController::class, 'que_hacemos'])->name('que-hacemos');
Route::get('/carreras', [App\Http\Controllers\FrontController::class, 'carreras'])->name('carreras');
Route::get('/proyecto-detalle/{slug}', [App\Http\Controllers\FrontController::class, 'proyecto_detalle'])->name('proyecto-detalle');
Route::get('/socios-comunitarios', [App\Http\Controllers\FrontController::class, 'socio_comunitarios'])->name('socios-comunitarios');
Route::post('/socios-comunitarios', [App\Http\Controllers\FrontController::class, 'formulario'])->name('socios-comunitarios');
Route::get('/tags/{slug}', [App\Http\Controllers\FrontController::class, 'tags'])->name('tags');

app/Models/Rol.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Rol extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = [
        'nombre',
        'area_id'
    ];
    public function Colaborador(): BelongsToMany
    {
        return $this->belongsToMany(Colaborador::class, 'colaborador_rols')->using(Colaborador_rol::class)->withTimestamps();
    }

    public function Area()
    {
        return $this->belongsTo(Area::class, 'area_id');
    }
}

app/Http/Controllers/Admin/RolController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Area;
use Illuminate\Http\Request;
use App\Models\Rol;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class RolController extends Controller
{

    public function index(Request $request)
    {
        $roles = Rol::all();
        if ($request) {
            $query = trim($request->get('search'));
            $roles = Rol::where('nombre', 'LIKE', '%' . $query . '%')
                ->orderBy('nombre', 'asc')
                ->paginate(10);
            return view('admin.rol.index', ['roles' => $roles, 'search' => $query]);
        }
        return view("admin.rol.index", compact("roles"));
    }

    public function create()
    {
        $areas = Area::all()->sortBy('nombre');
        return view("admin.rol.create", compact('areas'));
    }

    public function store(Request $request)
    {

        $rol = new Rol();
        $rol->area_id = ($request->input('area_id'));
        $rol->nombre        = request('nombre');
        $rol->save();
        return redirect()->route('rol.index');
    }

    public function edit($id)
    {
        $rol = Rol::findOrFail($id);
        $areas = Area::all()->sortBy('nombre');
        return view('admin.rol.edit', compact('rol', 'areas'));
    }

    public function update(Request $request, $id)
    {
        $registro = Rol::findOrFail($id);
        $registro->area_id = ($request->input('area_id'));
        $registro->fill($request->all());
        $registro->save();
        return redirect()->route('rol.index');
    }

    public function destroy($id)
    {
        $rol = Rol::find($id);
        $rol->delete();
        return redirect('admin/rol');
    }
}

resources/views/admin/rol/create.blade.php
@extends('layouts.menu')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"> Crear un nuevo rol</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin/rol">Rol</a></a></li>
                        <li class="breadcrumb-item"><a href="#">Crear</a></li>
                        <li class="breadcrumb-item active">{{'rol'}}</li>
                    </ol>
                </div><!-- /.col -->
            </div>

            <form action="{{ route('rol.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="jumbotron">
                    <div class="form-group">
                        <label for="nombre">Ingresar rol</label>
                        <input type="text" name="nombre" class="form-control" maxlength="100" required>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="area_id">Área Académica</label>
                        <select name="area_id" class="form-control selectpicker" data-style="btn-primary"
                            title="Elija una área académica" required>
                            @foreach ($areas as $area)
                            <option value="{{ $area->id }}">{{ $area->nombre }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <button type="submit" class="btn btn-success">Crear</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/rol/edit.blade.php
@extends('layouts.menu')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"> Editar un rol</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin/rol">Rol</a></a></li>
                        <li class="breadcrumb-item"><a href="#">Editar</a></li>
                        <li class="breadcrumb-item active">{{$rol->nombre}}</li>
                    </ol>
                </div><!-- /.col -->
            </div>
            <form action="{{ route('rol.update',$rol) }}" method="POST" enctype="multipart/form-data">
                @csrf @method('PUT')
                <div class="jumbotron">
                    <div class="form-group">
                        <label for="nombre">Ingresar rol</label>
                        <input type="text" name="nombre" class="form-control" maxlength="100"
                            value="{{ $rol->nombre }}">
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="area_id">Área Académica</label>
                        <select name="area_id" class="form-control selectpicker" data-style="btn-primary"
                            title="{{ $rol->area->año }}">
                            @foreach ($areas as $area)
                            <option value="{{ $area->id }}" {{ $rol->area_id == $area->id ? 'selected' :
                                '' }}>
                                {{ $area->nombre }}
                            </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Editar</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/rol/index.blade.php
@extends('layouts.menu')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Roles</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin/rol">Roles</a></li>
                        <li class="breadcrumb-item active"></li>
                    </ol>
                </div><!-- /.col -->
            </div>
            <hr>
            <div class="col-sm-12">
                <form class="form-inline ml-3 float-right">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" name="search" type="search" placeholder="Buscar"
                            aria-label="Search">
                        <div class="input-group-prepend">
                            <button type="submit" class="input-group-text">Buscar</button>

                        </div>
                    </div>
                </form>
            </div>
            <div class="col-sm-4">
                @if($search)
                <div class="alert alert-success" role="alert">
                    El resultado de la búsqueda de <strong>'{{$search}}'</strong> son:.
                </div>
                @endif
                </h6>
            </div>
            <a href="{{ route('rol.create') }}" class="btn btn-success">Nuevo</a>
            <a href="{{ route('area.index') }}" class="btn btn-success">Areas académicas</a>
            <table class="table table-striped">
                <thead>
                    <th>Nombre</th>
                    <th>Area</th>
                    <th>Acción</th>
                </thead>
                <tbody>
                    @forelse ($roles as $item)
                    <tr>
                        <td>{{ $item->nombre }}</td>
                        <td>{{ $item->area->nombre }}</td>
                        <td>
                            <a href="{{ route('rol.edit', $item->id) }}" class="btn btn-success">
                                <img src="/svg/edit.svg" alt="home-image" width="20">
                            </a>

                            <form method="POST" action="{{ route('rol.destroy', $item->id) }}" style="display:inline">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('¿Desea eliminar este registro?')">
                                    <img src="/svg/delete.svg" alt="home-image" width="20">
                                </button>
                            </form>
                        </td>
                    </tr>
                    @empty
                    @endforelse
                </tbody>
            </table>
            {{ $roles->links() }}
        </div>
    </div>
</div>
@endsection