routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    //ruta del admin

    Route::resource('/resumen', App\Http\Controllers\Admin\ResumenController::class);
    Route::resource('/colaborador', App\Http\Controllers\Admin\ColaboradorController::class);
    Route::resource('/rol', App\Http\Controllers\Admin\RolController::class);
    Route::resource('/socio_comunitario', App\Http\Controllers\Admin\Socio_comunitarioController::class);
    Route::resource('/facultad', App\Http\Controllers\Admin\FacultadController::class);
    Route::resource('/carrera', App\Http\Controllers\Admin\CarreraController::class);
    Route::resource('/tag', App\Http\Controllers\Admin\TagController::class);
    Route::resource('/competencia', App\Http\Controllers\Admin\CompetenciaController::class);
    Route::resource('/proyecto', App\Http\Controllers\Admin\ProyectoController::class);
    Route::resource('/home_noticias', App\Http\Controllers\Admin\Home_noticiasController::class);
    Route::resource('/testimonios', App\Http\Controllers\Admin\TestimoniosController::class);
    Route::resource('/que_hacemos', App\Http\Controllers\Admin\Que_hacemosController::class);
    Route::resource('/quienes_somos', App\Http\Controllers\Admin\Quienes_somosController::class);
    Route::resource('/home_carrusel', App\Http\Controllers\Admin\Home_carruselController::class);
    Route::resource('/ods', App\Http\Controllers\Admin\OdsController::class);
    Route::resource('/user', App\Http\Controllers\Admin\UserController::class);
    Route::resource('/periodo', App\Http\Controllers\Admin\PeriodoController::class);
    Route::resource('/solicitudes', App\Http\Controllers\Admin\SolicitudesController::class);
    Route::resource('/contacto', App\Http\Controllers\Admin\ContactoController::class);
    Route::resource('/area', App\Http\Controllers\Admin\AreaController::class);
    Route::resource('/grafico_carreras', App\Http\Controllers\Admin\GraficoController::class);
    Route::resource('/telefono_area', App\Http\Controllers\Admin\Telefono_areaController::class);
    Route::get('/grafico_carreras', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_carreras'])->name('grafico_carreras');
    Route::get('/grafico_socios', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_socios'])->name('grafico_socios');
    Route::get('/grafico_periodos', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_periodos'])->name('grafico_periodos');
    Route::get('/grafico_tags', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_tags'])->name('grafico_tags');
    Route::get('/grafico_ods', [App\Http\Controllers\Admin\GraficoController::class, 'grafico_ods'])->name('grafico_ods');
});

//ruta publica


Route::get('/', [App\Http\Controllers\FrontController::class, 'home'])->name('/');
Route::get('inicio', [App\Http\Controllers\FrontController::class, 'home'])->name('inicio');
Route::get('/noticias/{slug}', [App\Http\Controllers\FrontController::class, 'noticias'])->name('noticias');
Route::get('/blog-noticias', [App\Http\Controllers\FrontController::class, 'blognoticias'])->name('blog-noticias');
Route::get('/quienes-somos', [App\Http\Controllers\FrontController::class, 'quienes_somos'])->name('quienes-somos');
Route::get('/competencias-genericas', [App\Http\Controllers\FrontController::class, 'competencias'])->name('competencias-genericas');
Route::get('/contacto', [App\Http\Controllers\FrontController::class, 'contacto'])->name('contacto');
Route::get('/proyectos/{id}', [App\Http\Controllers\FrontController::class, 'proyectos'])->name('proyectos');
Route::get('/que-hacemos', [App\Http\Controllers\FrontController::class, 'que_hacemos'])->name('que-hacemos');
Route::get('/carreras', [App\Http\Controllers\FrontController::class, 'carreras'])->name('carreras');
Route::get('/proyecto-detalle/{slug}', [App\Http\Controllers\FrontController::class, 'proyecto_detalle'])->name('proyecto-detalle');
Route::get('/socios-comunitarios', [App\Http\Controllers\FrontController::class, 'socio_comunitarios'])->name('socios-comunitarios');
Route::post('/socios-comunitarios', [App\Http\Controllers\FrontController::class, 'formulario'])->name('socios-comunitarios');
Route::get('/tags/{slug}', [App\Http\Controllers\FrontController::class, 'tags'])->name('tags');

app/Models/Proyecto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Proyecto extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = [
        'slug',
        'nombre',
        'descripcion',
        'imagen',
        'carrera_id',
        'periodo_id',
        'socio_comunitario_id'
    ];

    public function Tag(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class, 'proyecto_tags')->using(Proyecto_tag::class)->withTimestamps();
    }

    public function Ods(): BelongsToMany
    {
        return $this->belongsToMany(Ods::class, 'proyecto_ods')->using(Proyecto_ods::class)->withTimestamps();
    }

    public function Users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'administrador_proyectos')->using(Administrador_proyecto::class)->withTimestamps();
    }

    public function Carrera()
    {
        return $this->belongsTo(Carrera::class, 'carrera_id');
    }

    public function Alumno(): HasMany
    {
        return $this->HasMany(Alumno::class, 'proyecto_id');
    }
    public function Socio_comunitario()
    {
        return $this->belongsTo(Socio_comunitario::class, 'socio_comunitario_id');
    }
    public function Periodo()
    {
        return $this->belongsTo(Periodo::class, 'periodo_id');
    }
}

app/Http/Controllers/Admin/ProyectoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Alumno;
use App\Models\Proyecto;
use App\Models\Socio_comunitario;
use App\Models\User;
use App\Models\Tag;
use App\Models\Ods;
use App\Models\Carrera;
use App\Models\Periodo;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;

class ProyectoController extends Controller
{
    // Otros métodos...

    public function generateUniqueSlug($name, $socioComunitarioId)
    {
        $slug = Str::slug($name);
        $count = Proyecto::where('nombre', $name)
                         ->where('socio_comunitario_id', $socioComunitarioId)
                         ->count();
    
        Log::debug("Nombre: {$name}, Socio Comunitario ID: {$socioComunitarioId}, Count: {$count}");
    
        return $count ? "{$slug}-{$count}" : $slug;
    }
   public function index(Request  $request)
    {
        $proyectos = Proyecto::all();
        $socio_comunitarios = Socio_comunitario::all();
        $tags = Tag::all();
        $carreras = Carrera::all();
        $odss = Ods::all();
        $alumnos = Alumno::all();
        $periodos = Periodo::all();
        if ($request) {
            $query = trim($request->get('search'));
            $proyectos = Proyecto::where('nombre', 'LIKE', '%' . $query . '%')
                ->orderBy('nombre', 'asc')
                ->paginate(10);
            return view('admin.proyecto.index', ['proyectos' => $proyectos, 'search' => $query]);
        }
        return view("admin.proyecto.index", compact('socio_comunitarios', 'tags', 'carreras', 'odss', 'alumnos', 'periodos'));
    }

    public function create()
    {
        $socio_comunitarios = Socio_comunitario::all()->sortBy('nombre');
        $users = User::all();
        $tags = Tag::all()->sortBy('nombre');
        $carreras = Carrera::all()->sortBy('nombre');
        $odss = Ods::all()->sortBy('nombre');
        $periodos = Periodo::all()->sortBy('año');
        return view('admin.proyecto.create', compact('socio_comunitarios', 'users', 'tags', 'carreras', 'odss', 'periodos'));
    }
    public function store(Request $request)
    {
        // Validación y lógica previa...

        // Generar un slug único
        $slug = $this->generateUniqueSlug($request->nombre, $request->socio_comunitario_id);
        Log::debug("Slug generado: {$slug}"); // Agregar un registro de depuración

        $proyecto = new Proyecto();
        $proyecto->carrera_id = ($request->input('carrera_id'));
        $proyecto->periodo_id = ($request->input('periodo_id'));
        $proyecto->socio_comunitario_id = ($request->input('socio_comunitario_id'));

        $proyecto->nombre         = request('nombre');
        $proyecto->slug           = $slug; // Usar el slug generado
        $proyecto->descripcion    = request('descripcion');

       if ($request->hasFile('imagen')) {
            $file = $request->imagen;
            $file->move(public_path() . '/img/admin/proyecto', $file->getClientOriginalName());
            $proyecto->imagen = $file->getClientOriginalName();
        }
        $proyecto->save();
  $proyecto_id = $proyecto->id;
     Log::debug("Proyecto guardado con ID: {$proyecto->id}"); // Agregar un registro de depuración
        $proyecto->Users()->attach($request->user()->id);
        $proyecto->Tag()->attach($request->input('tags'));
        $proyecto->Ods()->attach($request->input('odss'));

        $alumnos  = request('alumnos');
        foreach ($alumnos as $alumno) {
            if ($alumno != NULL) {
                $var = new Alumno();
                $var->proyecto_id = $proyecto_id;
                $var->nombre = $alumno;
                $var->save();
            }
        }
        return redirect()->route('proyecto.index');
    }

    public function edit($id)
    {

        $proyecto = Proyecto::findOrFail($id);
        $alumnos = Alumno::where('proyecto_id', $id)->orderBy('nombre', 'asc')->get();
        $socio_comunitarios = Socio_comunitario::all()->sortBy('nombre');
        $tags = Tag::all()->sortBy('nombre');
        $carreras = Carrera::all()->sortBy('nombre');
        $odss = Ods::all()->sortBy('nombre');
        $periodos = Periodo::all()->sortBy('nombre');
        return view('admin.proyecto.edit', compact('proyecto', 'socio_comunitarios', 'tags', 'carreras', 'odss', 'periodos', 'alumnos'));
    }

       
    public function update(Request $request, $id)
    {
        $proyecto = Proyecto::findOrFail($id);
        // Validación y lógica previa...

        // Generar un slug único
        $slug = $this->generateUniqueSlug($request->nombre, $request->socio_comunitario_id);
        Log::debug("Slug generado: {$slug}"); // Agregar un registro de depuración

        $proyecto->carrera_id = ($request->input('carrera_id'));
        $proyecto->periodo_id = ($request->input('periodo_id'));
        $proyecto->socio_comunitario_id = ($request->input('socio_comunitario_id'));
        $proyecto->nombre         = request('nombre');
        $proyecto->slug           = $slug; // Usar el slug generado
        $proyecto->descripcion    = request('descripcion');

     $imagen_anterior = $proyecto->imagen;
        if ($request->hasFile('imagen')) {
            $file = $request->imagen;
            $file->move(public_path() . '/img/admin/proyecto', $file->getClientOriginalName());
            $proyecto->imagen = $file->getClientOriginalName();
        }
        $proyecto->save();
        $proyecto->Tag()->sync($request->input('tags'));
        $proyecto->Ods()->sync($request->input('odss'));

        Alumno::where('proyecto_id', $id)->delete();
        $alumnos  = request('alumnos');
        foreach ($alumnos as $alumno) {
            if ($alumno != NULL) {
                $var = new Alumno();
                $var->proyecto_id = $id;
                $var->nombre = $alumno;
                $var->save();
            }
        }


        return redirect()->route('proyecto.index');
    }

public function destroy($id)
    {
        $proyecto = Proyecto::find($id);
        unlink(public_path('img/admin/proyecto/' . $proyecto->imagen));
        $proyecto->delete();
        return redirect('admin/proyecto');
    }
}

resources/views/admin/proyecto/create.blade.php
@extends('layouts.menu')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Crear un nuevo proyecto</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin/proyecto">Proyecto</a></a></li>
                        <li class="breadcrumb-item"><a href="#">Crear</a></li>
                        <li class="breadcrumb-item active">{{'proyecto'}}</li>
                    </ol>
                </div><!-- /.col -->
            </div>

            <form action="{{ route('proyecto.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="jumbotron">
                    <div class="form-group">
                        <label for="nombre">Ingresar nombre</label>
                        <input type="text" name="nombre" class="form-control" maxlength="100" required>
                    </div>

                    <div class="form-group">
                        <label for="descripcion">Ingresar descripción</label>
                        <textarea name="descripcion" class="form-control" maxlength="3000" required></textarea>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="carrera_id">Carrera</label>
                        <select name="carrera_id" class="form-control selectpicker" data-style="btn-primary"
                            title="Elija una carrera" required>
                            @foreach ($carreras as $carrera)
                            <option value="{{ $carrera->id }}">{{ $carrera->nombre }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="periodo_id">Periodo</label>
                        <select name="periodo_id" class="form-control selectpicker" data-style="btn-primary"
                            title="Elija un periodo" required>
                            @foreach ($periodos as $periodo)
                            <option value="{{ $periodo->id }}">{{ $periodo->año }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="socio_comunitario_id">Socio comunitario</label>
                        <select name="socio_comunitario_id" class="form-control selectpicker" data-style="btn-primary"
                            title="Elija un socio comunitario" required>
                            @foreach ($socio_comunitarios as $socio_comunitario)
                            <option value="{{ $socio_comunitario->id }}">{{ $socio_comunitario->nombre }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="odss">Ods</label>
                        <select name="odss[]" id="odss" class="form-control selectpicker" data-style="btn-primary"
                            title="Seleccionar objetivos de desarrollo sostenible" multiple required>
                            @foreach ($odss as $ods)
                            <option value="{{ $ods->id }}">{{ $ods->nombre }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="tags">Tags</label>
                        <select name="tags[]" id="tags" class="form-control selectpicker" data-style="btn-primary"
                            title="Seleccionar tags" multiple required>
                            @foreach ($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->nombre }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col">
                                <label for="alumnos1">Ingresar Alumno 1</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>

                            <div class="col">
                                <label for="alumnos2">Ingresar Alumno 2</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label for="alumnos3">Ingresar Alumno 3</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>

                            <div class="col">
                                <label for="alumnos4">Ingresar Alumno 4</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label for="alumnos5">Ingresar Alumno 5</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>

                            <div class="col">
                                <label for="alumnos6">Ingresar Alumno 6</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label for="alumnos7">Ingresar Alumno 7</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>

                            <div class="col">
                                <label for="alumnos8">Ingresar Alumno 8</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label for="alumnos9">Ingresar Alumno 9</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>

                            <div class="col">
                                <label for="alumnos10">Ingresar Alumno 10</label>
                                <input type="text" name="alumnos[]" class="form-control" maxlength="100">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="imagen">Ingresar imagen</label>
                        <br>
                        <img src="/img/admin/proyecto/proyecto.jpg" alt="">
                        <input type="file" name="imagen" required>
                    </div>
                </div>

                <button type="submit" class="btn btn-success">Crear</button>
            </form>

        </div>
    </div>
</div>
@endsection

resources/views/admin/proyecto/index.blade.php
@extends('layouts.menu')
@section('content')
<div class="container">
   
    <div class="row">
        <div class="col-sm-12">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Proyectos</h1>
                 
                </div><!-- /.col -->
              
                <div class="col-sm-6">
               
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin/proyecto">Proyectos</a></li>
                        <li class="breadcrumb-item active"></li>
                    </ol>
                </div><!-- /.col -->
            </div>
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">Hola {{ Auth::user()->name }}</h4>
                <p>Si va a agragar un proyecto, por favor siga esta recomedación:<br>
                    1-Asegurese de que el socio comunitario y los tags  esten registrado en la sección <strong>"Socios Comunitario"y "Tags"</strong>  perteneciente al proyecto <br>
                    2-Que la imagen tenga un formato <strong>".jpg" o ".png"</strong>.<br>
                    3-Respete los caracteres de los campos solicitados.
                </p>
               
            </div>
            <hr>
            <div class="col-sm-12">
                <form class="form-inline ml-3 float-right">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" name="search" type="search" placeholder="Buscar"
                            aria-label="Search">
                        <div class="input-group-prepend">
                            <button type="submit" class="input-group-text">Buscar</button>

                        </div>
                    </div>
                </form>
            </div>
            <div class="col-sm-4">
                @if($search)
                <div class="alert alert-success" role="alert">
                    El resultado de la búsqueda de <strong>'{{$search}}'</strong> son:.
                </div>
                @endif
                </h6>
            </div>
            <br>
            <a href="{{ route('proyecto.create') }}" class="btn btn-success" style='display:inline'>Nuevo</a>
            <a href="{{ route('carrera.index') }}" class="btn btn-success" style='display:inline'>Carreras</a>
            <a href="{{ route('tag.index') }}" class="btn btn-success" style='display:inline'>Tags</a>
            <a href="{{ route('socio_comunitario.index') }}" class="btn btn-success" style='display:inline'>Socios
                comunitario</a>
            <a href="{{ route('ods.index') }}" class="btn btn-success" style='display:inline'>Ods</a>
            <a href="{{ route('periodo.index') }}" class="btn btn-success" style='display:inline'>Periodo</a>
            <table class="table table-striped">
                <thead>
                    <th>Nombre</th>
                    <th>Imagen</th>
                    <th>Carrera</th>
                    <th>Socio Comunitarios</th>
                    <th>Ods</th>
                    <th>Tags</th>
                    <th>Alumnos</th>
                    <th>Periodo</th>
                    <th>Acción</th>
                </thead>
                <tbody>
                    @forelse ($proyectos as $proyecto)
                    <tr>
                        <td>{{ $proyecto->nombre }}</td>
                        <td><img src="/img/admin/proyecto/{{ $proyecto->imagen }}" alt="" width="50" height="50"></td>
                        <td>{{ $proyecto->Carrera->nombre }}</td>
                        <td>{{ $proyecto->Socio_comunitario->nombre }}</td>

                        <td>
                            @forelse ($proyecto->Ods as $ods)
                            {{ $ods->nombre; }}
                            <br>
                            @empty
                            @endforelse
                        </td>

                        <td>
                            @forelse ($proyecto->Tag as $tag)
                            {{ $tag->nombre; }}
                            <br>
                            @empty
                            @endforelse
                        </td>

                        <td>
                            @forelse ($proyecto->Alumno as $alumno)
                            {{ $alumno->nombre; }}
                            <br>
                            @empty
                            @endforelse
                        </td>
                        <td>{{ $proyecto->Periodo->año }}</td>

                        <td>
                            <a href="{{ route('proyecto.edit', $proyecto->id) }}" class="btn btn-success"
                                style="margin-bottom: 10px;">
                                <img src="/svg/edit.svg" alt="home-image" width="20">
                            </a>

                            <form method="POST" action="{{ route('proyecto.destroy', $proyecto->id) }}"
                                style="display:inline">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('¿Desea eliminar este registro?')">
                                    <img src="/svg/delete.svg" alt="home-image" width="20">
                                </button>
                            </form>
                        </td>
                    </tr>
                    @empty
                    @endforelse
                </tbody>
            </table>
            {{ $proyectos->links() }}
        </div>
    </div>
  
</div>
@endsection